apps/search/urls.py
from django.conf.urls import url

from apps.search.views import ProcessRecipeSearch

app_name = "search"

urlpatterns = [
    url(
        r"^process_recipe_search/$",
        ProcessRecipeSearch.as_view(),
        name="process_recipe_search",
    ),
]

wimf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^$", include("apps.home.urls", namespace="home")),
    url(r"^recipes/", include("apps.recipes.urls", namespace="recipes")),
    url(r"^search/", include("apps.search.urls", namespace="search")),
]

apps/search/forms.py
from urllib.parse import urlencode

from common.utils import cleanup_ingredients
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


class RecipeSearchForm(forms.Form):
    """
    Simple search form config, for validating against
    """

    def __init__(self, *args, **kwargs):
        super(RecipeSearchForm, self).__init__(*args, **kwargs)

    ingredients = forms.CharField(label="Ingredients", max_length=2000, required=True)

apps/search/views.py
from collections import defaultdict

import pygal
from common.utils import (
    lc_csv_str_of_ingredients,
    lc_whitespaced_str_of_ingredients,
    sorted_ingredients_as_csv,
    split_str_on_whitespace,
)
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from pygal.style import CleanStyle
from services.es_search import RecipeSearch


def percentage_of_ingredients_matched(query_params_ingredients):
    """
    Method to calculate the percentage of ingredient keywords matched for each Elasticsearch hit.
    Return a closure to cache some calculated values (from query params, which are the same for each call)

    :param query_params_ingredients(str), of space delimited keywords from the user's search:
    :return: get_percentage_matched (function)
    """

    # Get the query params values, which don't change between calls and are hashable
    # Lower case the list so they are now separate keywords
    query_params_ingredients_list = lc_whitespaced_str_of_ingredients(
        query_params_ingredients
    )

    def get_percentage_matched(recipe_ingredients):
        """
        Cycle through recipe ingredients, which may contain multi-word phrases like 'black pepper'
        and for each of those check whether there's a user's search keyword match: increment the counter
        for that recipe ingredient if so.
        At the end we can create a set from the dict names to see the overall match of phrases
        rather than single words.  This is more accurate.

        :param recipe_ingredients(str), from the hits returned by search
        :return: matched words(str), the percentage matched(float to 2 decimal places)
        """
        recipe_ingredients = lc_csv_str_of_ingredients(recipe_ingredients)
        matched_phrases = defaultdict(int)
        for recipe_ingredient in recipe_ingredients:
            for ingredient in query_params_ingredients_list:
                if ingredient in split_str_on_whitespace(recipe_ingredient):
                    matched_phrases[recipe_ingredient] += 1

        matched_phrases_set = set(matched_phrases.keys())
        recipe_ingredients_set = set(recipe_ingredients)
        # Calculate the percentage of matches of matched words against the whole recipe ingredients keyword list
        percentage_matched = (
            len(matched_phrases_set) / len(recipe_ingredients_set)
        ) * 100
        # Round to 2 decimal places
        percentage_matched = round(percentage_matched, 2)
        # return a string of sorted, space delimited matched words
        matched_words = ", ".join(sorted(list(matched_phrases_set)))
        return matched_words, percentage_matched

    return get_percentage_matched


class ProcessRecipeSearch(View):
    """
    View for processing recipe search form
    """

    def get(self, request):
        """ HTTP Get
        :Params
            request: HTTP request obj passed to class views
            reverse (Str): reversed request path to search view

        :Return
            Rendered results template, with the recipes found from the search
        """

        # Get our request params and do the search in Elasticsearch, via services
        query_params = request.GET
        recipe_search = RecipeSearch()
        recipes = recipe_search.do_search({"ingredients": query_params["ingredients"]})

        # Nothing found: return to home page with msg
        if len(recipes) == 0:
            messages.add_message(
                request,
                messages.ERROR,
                "Sorry, no recipes were found for those ingredients",
            )
            search_url = reverse("home:index")
            return HttpResponseRedirect(search_url)

        # Success: we have some results, so turn them into graph images for display
        # Create a gauge chart showing what percentage of ingredient keywords we matched, for each match
        gauge_chart = self._make_gauge_chart(query_params, recipes)

        # Create a bar chart showing what percentage of ingredient keywords we matched, for each match
        bar_chart = self._make_bar_chart(recipes)

        # Create a pie chart showing how Elasticsearch rated our matching recipes
        pie_chart = self._make_pie_chart(recipes)

        # Populate context var for rendering, with the charts we've created
        context = {
            "recipes": recipes,
            "gauge_chart": gauge_chart.render_data_uri(),
            "bar_chart": bar_chart.render_data_uri(),
            "pie_chart": pie_chart.render_data_uri(),
        }
        return render(request, "recipes/search_results.html", context)

    def _make_gauge_chart(self, query_params, recipes):
        """
        :param query_params(query dict):
        :param recipes(list of dicts of hits returned from Elasticsearch):
        :return(obj): gauge_chart
        """

        get_percentage_matched = percentage_of_ingredients_matched(
            query_params["ingredients"]
        )
        gauge_chart = pygal.SolidGauge(
            width=1300, height=1300, inner_radius=0.50, style=CleanStyle
        )
        percent_formatter = lambda x: "{:.10g}%".format(x)
        gauge_chart.value_formatter = percent_formatter
        for recipe in recipes:
            (matched_words, percentage_matched) = get_percentage_matched(
                recipe["ingredients"]
            )
            gauge_chart.add(
                {
                    "title": recipe["name"],
                    "tooltip": "Has ingredients: "
                    + sorted_ingredients_as_csv(recipe["ingredients"])
                    + " and you matched: "
                    + matched_words,
                },
                [
                    {
                        "value": percentage_matched,
                        "max_value": 100,
                        "xlink": {"href": recipe["url"], "target": "_blank"},
                    }
                ],
            )

        return gauge_chart

    def _make_bar_chart(self, recipes):
        """
        :param recipes(list of dicts of hits returned from search):
        :return(obj): bar_chart
        """

        bar_chart = pygal.Bar(width=1300, height=800, style=CleanStyle)
        for recipe in recipes:
            bar_chart.add(
                {
                    "title": recipe["name"],
                    "tooltip": "Has ingredients: "
                    + sorted_ingredients_as_csv(recipe["ingredients"]),
                },
                [
                    {
                        "value": int(round(recipe["score"] * 100)),
                        "xlink": {"href": recipe["url"], "target": "_blank"},
                    }
                ],
            )

        return bar_chart

    def _make_pie_chart(self, recipes):
        """
        :param recipes(list of dicts of hits returned from search):
        :return(obj): pie_chart
        """

        pie_chart = pygal.Pie(width=1300, height=1300, style=CleanStyle)
        for recipe in recipes:
            pie_chart.add(
                {
                    "title": recipe["name"],
                    "tooltip": "Has ingredients: "
                    + sorted_ingredients_as_csv(recipe["ingredients"]),
                },
                [
                    {
                        "value": int(round(recipe["score"] * 100)),
                        "xlink": {"href": recipe["url"], "target": "_blank"},
                    }
                ],
            )

        return pie_chart

apps/search/templates/search/recipe_search.html
{% load static %}

                    <!-- Search Functionality -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Search for recipes using ingredients found in your fridge or cupboards!</h3>
                        </div>
                        <div class="panel-body">
                            <!-- Display any errors from previous form submission -->
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-danger">
                                        <strong>
                                            {% if message.level == default_message_levels_error and message != "" %}
                                                {{ message }}
                                            {% endif %}
                                        </strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <form class="global-form" name="recipe_search_form" id="recipe_search_form" method="get" action="{%url 'search:process_recipe_search'%}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <p>
                                        {% if form.ingredients.errors %}
                                            <div class="alert alert-danger">
                                            {% for error in form.ingredients.errors %}
                                                <strong>{{ error }}</strong><br/>
                                            {% endfor %}
                                            </div>
                                        {% endif %}
                                        <label for="ingredients" class="home-label-required">Ingredient keywords</label>
                                        <input type="text" id="ingredients" name="ingredients" class="form-control" placeholder="beef tomatoes wine thyme" value="{{ form.ingredients.value|default_if_none:"" }}"/>
                                    </p>
                                </div>
                                <button type="submit" class="btn btn-default submit-button">Submit</button>
                            </form>
                        </div>
                        <!-- /.search functionality -->
                    </div>